// Package changelog implements the shared change log used by all agents
// (Claude Code, OpenCode, humans). Every change is recorded as an
// independent markdown fragment in changelog.d/ — one file per change, with
// a name unique per timestamp+agent — so two agents working in parallel
// never edit the same file. CHANGELOG.md is generated by compiling the
// fragments in chronological order and is never edited by hand.
package changelog

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Entry is a single change recorded by an agent.
type Entry struct {
	Timestamp time.Time
	Agent     string
	Summary   string
	Files     []string
}

// Header heads the generated CHANGELOG.md.
const Header = `# Changelog

<!-- GENERATED FILE: do not edit by hand. -->
<!-- Source: fragments in changelog.d/*.md -->
<!-- Regenerate: make changelog  (or: go run ./cmd/changelog compile) -->
`

// ParseFragment reads a markdown fragment with front matter delimited by
// "---" lines. The body after the front matter is the change summary.
func ParseFragment(data []byte) (Entry, error) {
	var e Entry
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	rest, ok := strings.CutPrefix(text, "---\n")
	if !ok {
		return e, fmt.Errorf("fragment has no opening front matter (---)")
	}
	head, body, ok := strings.Cut(rest, "\n---")
	if !ok {
		return e, fmt.Errorf("front matter has no closing delimiter (---)")
	}

	inFiles := false
	for _, line := range strings.Split(head, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if inFiles && strings.HasPrefix(trimmed, "- ") {
			e.Files = append(e.Files, strings.TrimSpace(strings.TrimPrefix(trimmed, "- ")))
			continue
		}
		inFiles = false
		key, value, found := strings.Cut(trimmed, ":")
		if !found {
			return e, fmt.Errorf("invalid front matter line: %q", trimmed)
		}
		value = strings.TrimSpace(value)
		switch strings.TrimSpace(key) {
		case "timestamp":
			ts, err := time.Parse(time.RFC3339, value)
			if err != nil {
				return e, fmt.Errorf("invalid timestamp %q: %w", value, err)
			}
			e.Timestamp = ts.UTC()
		case "agent":
			e.Agent = value
		case "files":
			inFiles = true
		}
	}

	e.Summary = strings.TrimSpace(body)

	if e.Timestamp.IsZero() {
		return e, fmt.Errorf("fragment is missing the timestamp field")
	}
	if e.Agent == "" {
		return e, fmt.Errorf("fragment is missing the agent field")
	}
	if e.Summary == "" {
		return e, fmt.Errorf("fragment has no summary (empty body)")
	}
	return e, nil
}

// LoadDir reads every *.md fragment in a directory (ignoring README.md) and
// returns the entries sorted in ascending chronological order.
func LoadDir(dir string) ([]Entry, error) {
	items, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var entries []Entry
	for _, item := range items {
		name := item.Name()
		if item.IsDir() || !strings.HasSuffix(name, ".md") || strings.EqualFold(name, "README.md") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		entry, err := ParseFragment(data)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		entries = append(entries, entry)
	}
	sortChronological(entries)
	return entries, nil
}

// Render produces the full CHANGELOG.md content: one section per date
// (most recent first) and, within each date, changes in ascending
// chronological order. Each entry starts with the change explanation and
// ends with a metadata line: UTC date/time, agent and affected files.
func Render(entries []Entry) string {
	sorted := make([]Entry, len(entries))
	copy(sorted, entries)
	sortChronological(sorted)

	byDate := map[string][]Entry{}
	var dates []string
	for _, e := range sorted {
		d := e.Timestamp.Format("2006-01-02")
		if _, seen := byDate[d]; !seen {
			dates = append(dates, d)
		}
		byDate[d] = append(byDate[d], e)
	}

	var b strings.Builder
	b.WriteString(Header)
	for i := len(dates) - 1; i >= 0; i-- {
		d := dates[i]
		fmt.Fprintf(&b, "\n## %s\n\n", d)
		for _, e := range byDate[d] {
			fmt.Fprintf(&b, "- %s\n", e.Summary)
			for _, f := range e.Files {
				fmt.Fprintf(&b, "  - `%s`\n", f)
			}
			fmt.Fprintf(&b, "  - _%s — %s_\n", e.Timestamp.Format("2006-01-02 15:04:05 UTC"), e.Agent)
		}
	}
	return b.String()
}

func sortChronological(entries []Entry) {
	sort.SliceStable(entries, func(i, j int) bool {
		return entries[i].Timestamp.Before(entries[j].Timestamp)
	})
}
