// changelog is the tool shared by all agents to record changes without
// collisions: every change is a new fragment in changelog.d/ (existing files
// are never edited) and CHANGELOG.md is regenerated by compiling the
// fragments in chronological order.
//
// Usage:
//
//	go run ./cmd/changelog new -agent <name> -summary "<summary>" [-files a.go,b.go]
//	go run ./cmd/changelog compile
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/mRemoteNG/mremoteng-go/internal/changelog"
)

const fragmentsDir = "changelog.d"

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	switch os.Args[1] {
	case "new":
		runNew(os.Args[2:])
	case "compile":
		runCompile()
	default:
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `usage:
  changelog new -agent <name> -summary "<summary>" [-files a.go,b.go]
      Create a fragment in changelog.d/ and recompile CHANGELOG.md.
      Without -files, affected files are detected from git.
  changelog compile
      Regenerate CHANGELOG.md from the fragments.`)
}

func runNew(args []string) {
	fs := flag.NewFlagSet("new", flag.ExitOnError)
	agent := fs.String("agent", "", "agent name (claude-code, opencode, ...)")
	summary := fs.String("summary", "", "one-line change summary, imperative mood")
	files := fs.String("files", "", "comma-separated list of affected files (optional)")
	_ = fs.Parse(args)

	if *agent == "" || *summary == "" {
		fmt.Fprintln(os.Stderr, "error: -agent and -summary are required")
		fs.Usage()
		os.Exit(2)
	}

	root := repoRoot()
	var affected []string
	if *files != "" {
		for _, f := range strings.Split(*files, ",") {
			if f = strings.TrimSpace(f); f != "" {
				affected = append(affected, f)
			}
		}
	} else {
		affected = changedFiles(root)
	}

	now := time.Now().UTC()
	path := fragmentPath(root, now, *agent, *summary)

	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "timestamp: %s\n", now.Format(time.RFC3339))
	fmt.Fprintf(&b, "agent: %s\n", *agent)
	if len(affected) > 0 {
		b.WriteString("files:\n")
		for _, f := range affected {
			fmt.Fprintf(&b, "  - %s\n", f)
		}
	}
	b.WriteString("---\n\n")
	b.WriteString(strings.TrimSpace(*summary) + "\n")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
	fmt.Println("fragment created:", path)
	compile(root)
}

func runCompile() {
	compile(repoRoot())
}

func compile(root string) {
	entries, err := changelog.LoadDir(filepath.Join(root, fragmentsDir))
	if err != nil {
		fatal(err)
	}
	out := filepath.Join(root, "CHANGELOG.md")
	if err := os.WriteFile(out, []byte(changelog.Render(entries)), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("CHANGELOG.md regenerated (%d changes)\n", len(entries))
}

// fragmentPath builds a unique, chronologically sortable file name. If two
// agents record within the same second with the same summary, a numeric
// suffix is appended instead of overwriting.
func fragmentPath(root string, ts time.Time, agent, summary string) string {
	base := fmt.Sprintf("%s-%s-%s", ts.Format("20060102T150405Z"), slug(agent), slug(summary))
	for i := 0; ; i++ {
		name := base
		if i > 0 {
			name = fmt.Sprintf("%s-%d", base, i)
		}
		path := filepath.Join(root, fragmentsDir, name+".md")
		if _, err := os.Stat(path); os.IsNotExist(err) {
			return path
		}
	}
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func slug(s string) string {
	s = nonAlnum.ReplaceAllString(strings.ToLower(s), "-")
	s = strings.Trim(s, "-")
	if len(s) > 40 {
		s = strings.Trim(s[:40], "-")
	}
	if s == "" {
		s = "change"
	}
	return s
}

// changedFiles lists modified and new files according to git, excluding the
// changelog system itself.
func changedFiles(root string) []string {
	seen := map[string]bool{}
	var out []string
	for _, args := range [][]string{
		{"diff", "--name-only", "HEAD"},
		{"ls-files", "--others", "--exclude-standard"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = root
		data, err := cmd.Output()
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || seen[line] || line == "CHANGELOG.md" || strings.HasPrefix(line, fragmentsDir+"/") {
				continue
			}
			seen[line] = true
			out = append(out, line)
		}
	}
	sort.Strings(out)
	return out
}

func repoRoot() string {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		wd, _ := os.Getwd()
		return wd
	}
	return strings.TrimSpace(string(out))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
