package csv

type columnSource uint8

const (
	columnMeta columnSource = iota
	columnValue
	columnInheritance
)

type filterKind uint8

const (
	filterNone filterKind = iota
	filterUsername
	filterPassword
	filterDomain
)

type column struct {
	// header is positional. It may intentionally name a different row value or
	// be empty where the published C# header accidentally merged two columns.
	header string
	source columnSource
	field  string
	filter filterKind
}

// columns follows the C# row order. The header fields preserve the published
// defects so files written here are byte-structurally compatible with C#.
var columns = []column{
	{header: "Name", source: columnMeta},
	{header: "Id", source: columnMeta},
	{header: "Parent", source: columnMeta},
	{header: "NodeType", source: columnMeta},
	{header: "Description", source: columnValue, field: "Description"},
	{header: "Icon", source: columnValue, field: "Icon"},
	{header: "Panel", source: columnValue, field: "Panel"},
	{header: "TabColor", source: columnValue, field: "TabColor"},
	{header: "ConnectionFrameColor", source: columnValue, field: "ConnectionFrameColor"},
	{header: "Username", source: columnValue, field: "Username", filter: filterUsername},
	{header: "Password", source: columnValue, field: "Password", filter: filterPassword},
	{header: "Domain", source: columnValue, field: "Domain", filter: filterDomain},
	{header: "Hostname", source: columnValue, field: "Hostname"},
	{header: "Port", source: columnValue, field: "Port"},
	{header: "VmId", source: columnValue, field: "VMID"},
	{header: "Protocol", source: columnValue, field: "Protocol"},
	{header: "SSHTunnelConnectionName", source: columnValue, field: "SSHTunnelConnectionName"},
	{header: "OpeningCommand", source: columnValue, field: "OpeningCommand"},
	{header: "SSHOptions", source: columnValue, field: "SSHOptions"},
	{header: "PuttySession", source: columnValue, field: "PuttySession"},
	{header: "ConnectToConsole", source: columnValue, field: "UseConsoleSession"},
	{header: "UseCredSsp", source: columnValue, field: "UseCredSsp"},
	{header: "UseRestrictedAdmin", source: columnValue, field: "UseRestrictedAdmin"},
	{header: "UseRCG", source: columnValue, field: "UseRCG"},
	{header: "UseRedirectionServerName", source: columnValue, field: "UseRedirectionServerName"},
	{header: "UseVmId", source: columnValue, field: "UseVMID"},
	{header: "UseEnhancedMode", source: columnValue, field: "UseEnhancedMode"},
	{header: "RenderingEngine", source: columnValue, field: "RenderingEngine"},
	{header: "RDPAuthenticationLevel", source: columnValue, field: "RDPAuthenticationLevel"},
	{header: "LoadBalanceInfo", source: columnValue, field: "LoadBalanceInfo"},
	{header: "Colors", source: columnValue, field: "Colors"},
	{header: "Resolution", source: columnValue, field: "Resolution"},
	{header: "AutomaticResize", source: columnValue, field: "AutomaticResize"},
	{header: "DisplayWallpaper", source: columnValue, field: "DisplayWallpaper"},
	{header: "DisplayThemes", source: columnValue, field: "DisplayThemes"},
	{header: "EnableFontSmoothing", source: columnValue, field: "EnableFontSmoothing"},
	{header: "EnableDesktopComposition", source: columnValue, field: "EnableDesktopComposition"},
	{header: "DisableFullWindowDrag", source: columnValue, field: "DisableFullWindowDrag"},
	{header: "DisableMenuAnimations", source: columnValue, field: "DisableMenuAnimations"},
	{header: "DisableCursorShadow", source: columnValue, field: "DisableCursorShadow"},
	{header: "DisableCursorBlinking", source: columnValue, field: "DisableCursorBlinking"},
	{header: "CacheBitmaps", source: columnValue, field: "CacheBitmaps"},
	{header: "RedirectDiskDrives", source: columnValue, field: "RedirectDiskDrives"},
	{header: "RedirectDiskDrivesCustomRedirectPorts", source: columnValue, field: "RedirectDiskDrivesCustom"},
	{source: columnValue, field: "RedirectPorts"},
	{header: "RedirectPrinters", source: columnValue, field: "RedirectPrinters"},
	{header: "RedirectClipboard", source: columnValue, field: "RedirectClipboard"},
	{header: "RedirectSmartCards", source: columnValue, field: "RedirectSmartCards"},
	{header: "RedirectSound", source: columnValue, field: "RedirectSound"},
	{header: "RedirectKeys", source: columnValue, field: "RedirectKeys"},
	{header: "PreExtApp", source: columnValue, field: "PreExtApp"},
	{header: "PostExtApp", source: columnValue, field: "PostExtApp"},
	{header: "MacAddress", source: columnValue, field: "MacAddress"},
	{header: "UserField", source: columnValue, field: "UserField"},
	{header: "EnvironmentTags", source: columnValue, field: "EnvironmentTags"},
	{header: "ExtApp", source: columnValue, field: "ExtApp"},
	{header: "Favorite", source: columnValue, field: "Favorite"},
	{header: "VNCCompression", source: columnValue, field: "VNCCompression"},
	{header: "VNCEncoding", source: columnValue, field: "VNCEncoding"},
	{header: "VNCAuthMode", source: columnValue, field: "VNCAuthMode"},
	{header: "VNCProxyType", source: columnValue, field: "VNCProxyType"},
	{header: "VNCProxyIP", source: columnValue, field: "VNCProxyIP"},
	{header: "VNCProxyPort", source: columnValue, field: "VNCProxyPort"},
	{header: "VNCProxyUsername", source: columnValue, field: "VNCProxyUsername"},
	{header: "VNCProxyPassword", source: columnValue, field: "VNCProxyPassword"},
	{header: "VNCColors", source: columnValue, field: "VNCColors"},
	{header: "VNCSmartSizeMode", source: columnValue, field: "VNCSmartSizeMode"},
	{header: "VNCViewOnly", source: columnValue, field: "VNCViewOnly"},
	{header: "RDGatewayUsageMethod", source: columnValue, field: "RDGatewayUsageMethod"},
	{header: "RDGatewayHostname", source: columnValue, field: "RDGatewayHostname"},
	{header: "RDGatewayUseConnectionCredentials", source: columnValue, field: "RDGatewayUseConnectionCredentials"},
	{header: "RDGatewayUsername", source: columnValue, field: "RDGatewayUsername"},
	{header: "RDGatewayPassword", source: columnValue, field: "RDGatewayPassword"},
	{header: "RDGatewayDomain", source: columnValue, field: "RDGatewayDomain"},
	{header: "RDGatewayExternalCredentialProvider", source: columnValue, field: "RDGatewayExternalCredentialProvider"},
	{header: "RDGatewayUserViaAPI", source: columnValue, field: "RDGatewayUserViaAPI"},
	{header: "RedirectAudioCapture", source: columnValue, field: "RedirectAudioCapture"},
	{header: "RdpVersion", source: columnValue, field: "RDPVersion"},
	{header: "RDPStartProgram", source: columnValue, field: "RDPStartProgram"},
	{header: "RDPStartProgramWorkDir", source: columnValue, field: "RDPStartProgramWorkDir"},
	{header: "UserViaAPI", source: columnValue, field: "UserViaAPI"},
	{header: "EC2InstanceId", source: columnValue, field: "EC2InstanceID"},
	{header: "EC2Region", source: columnValue, field: "EC2Region"},
	{header: "ExternalCredentialProvider", source: columnValue, field: "ExternalCredentialProvider"},
	{header: "ExternalAddressProvider", source: columnValue, field: "ExternalAddressProvider"},

	{header: "InheritCacheBitmaps", source: columnInheritance, field: "CacheBitmaps"},
	{header: "InheritColors", source: columnInheritance, field: "Colors"},
	{header: "InheritDescription", source: columnInheritance, field: "Description"},
	{header: "InheritDisplayThemes", source: columnInheritance, field: "DisplayThemes"},
	{header: "InheritDisplayWallpaper", source: columnInheritance, field: "DisplayWallpaper"},
	{header: "InheritEnableFontSmoothing", source: columnInheritance, field: "EnableFontSmoothing"},
	{header: "InheritEnableDesktopComposition", source: columnInheritance, field: "EnableDesktopComposition"},
	{header: "InheritDisableFullWindowDrag", source: columnInheritance, field: "DisableFullWindowDrag"},
	{header: "InheritDisableMenuAnimations", source: columnInheritance, field: "DisableMenuAnimations"},
	{header: "InheritDisableCursorShadow", source: columnInheritance, field: "DisableCursorShadow"},
	{header: "InheritDisableCursorBlinking", source: columnInheritance, field: "DisableCursorBlinking"},
	{header: "InheritDomain", source: columnInheritance, field: "Domain"},
	{header: "InheritIcon", source: columnInheritance, field: "Icon"},
	{header: "InheritPanel", source: columnInheritance, field: "Panel"},
	{header: "InheritTabColor", source: columnInheritance, field: "TabColor"},
	{header: "InheritConnectionFrameColor", source: columnInheritance, field: "ConnectionFrameColor"},
	{header: "InheritPassword", source: columnInheritance, field: "Password"},
	{header: "InheritPort", source: columnInheritance, field: "Port"},
	{header: "InheritProtocol", source: columnInheritance, field: "Protocol"},
	{header: "InheritSSHTunnelConnectionName", source: columnInheritance, field: "SSHTunnelConnectionName"},
	{header: "InheritOpeningCommand", source: columnInheritance, field: "OpeningCommand"},
	{header: "InheritSSHOptions", source: columnInheritance, field: "SSHOptions"},
	{header: "InheritPuttySession", source: columnInheritance, field: "PuttySession"},
	{header: "InheritRedirectDiskDrives", source: columnInheritance, field: "RedirectDiskDrives"},
	{header: "InheritRedirectDiskDrivesCustom", source: columnInheritance, field: "RedirectDiskDrivesCustom"},
	{header: "InheritRedirectKeys", source: columnInheritance, field: "RedirectKeys"},
	{header: "InheritRedirectPorts", source: columnInheritance, field: "RedirectPorts"},
	{header: "InheritRedirectPrinters", source: columnInheritance, field: "RedirectPrinters"},
	{header: "InheritRedirectClipboard", source: columnInheritance, field: "RedirectClipboard"},
	{header: "InheritRedirectSmartCards", source: columnInheritance, field: "RedirectSmartCards"},
	{header: "InheritRedirectSound", source: columnInheritance, field: "RedirectSound"},
	{header: "InheritResolution", source: columnInheritance, field: "Resolution"},
	{header: "InheritAutomaticResize", source: columnInheritance, field: "AutomaticResize"},
	{header: "InheritUseConsoleSession", source: columnInheritance, field: "UseConsoleSession"},
	{header: "InheritUseCredSsp", source: columnInheritance, field: "UseCredSsp"},
	{header: "InheritUseRestrictedAdmin", source: columnInheritance, field: "UseRestrictedAdmin"},
	{header: "InheritUseRCG", source: columnInheritance, field: "UseRCG"},
	{header: "InheritUseRedirectionServerName", source: columnInheritance, field: "UseRedirectionServerName"},
	{header: "InheritUseVmId", source: columnInheritance, field: "UseVMID"},
	{header: "InheritUseEnhancedMode", source: columnInheritance, field: "UseEnhancedMode"},
	{header: "InheritVmId", source: columnInheritance, field: "VMID"},
	{header: "InheritRenderingEngine", source: columnInheritance, field: "RenderingEngine"},
	{header: "InheritUsername", source: columnInheritance, field: "Username"},
	{header: "InheritRDPAuthenticationLevel", source: columnInheritance, field: "RDPAuthenticationLevel"},
	{header: "InheritLoadBalanceInfo", source: columnInheritance, field: "LoadBalanceInfo"},
	{header: "InheritPreExtApp", source: columnInheritance, field: "PreExtApp"},
	{header: "InheritPostExtApp", source: columnInheritance, field: "PostExtApp"},
	{header: "InheritMacAddress", source: columnInheritance, field: "MacAddress"},
	{header: "InheritUserField", source: columnInheritance, field: "UserField"},
	{header: "InheritEnvironmentTags", source: columnInheritance, field: "EnvironmentTags"},
	{header: "InheritFavorite", source: columnInheritance, field: "Favorite"},
	{header: "InheritExtApp", source: columnInheritance, field: "ExtApp"},
	{header: "InheritVNCCompression", source: columnInheritance, field: "VNCCompression"},
	{header: "InheritVNCEncoding", source: columnInheritance, field: "VNCEncoding"},
	{header: "InheritVNCAuthMode", source: columnInheritance, field: "VNCAuthMode"},
	{header: "InheritVNCProxyType", source: columnInheritance, field: "VNCProxyType"},
	{header: "InheritVNCProxyIP", source: columnInheritance, field: "VNCProxyIP"},
	{header: "InheritVNCProxyPort", source: columnInheritance, field: "VNCProxyPort"},
	{header: "InheritVNCProxyUsername", source: columnInheritance, field: "VNCProxyUsername"},
	{header: "InheritVNCProxyPassword", source: columnInheritance, field: "VNCProxyPassword"},
	{header: "InheritVNCColors", source: columnInheritance, field: "VNCColors"},
	{header: "InheritVNCSmartSizeMode", source: columnInheritance, field: "VNCSmartSizeMode"},
	{header: "InheritVNCViewOnly", source: columnInheritance, field: "VNCViewOnly"},
	{header: "InheritRDGatewayUsageMethod", source: columnInheritance, field: "RDGatewayUsageMethod"},
	{header: "InheritRDGatewayHostname", source: columnInheritance, field: "RDGatewayHostname"},
	{header: "InheritRDGatewayUseConnectionCredentials", source: columnInheritance, field: "RDGatewayUseConnectionCredentials"},
	{header: "InheritRDGatewayUsername", source: columnInheritance, field: "RDGatewayUsername"},
	{header: "InheritRDGatewayPassword", source: columnInheritance, field: "RDGatewayPassword"},
	{header: "InheritRDGatewayDomain", source: columnInheritance, field: "RDGatewayDomain"},
	{header: "InheritRDGatewayExternalCredentialProvider", source: columnInheritance, field: "RDGatewayExternalCredentialProvider"},
	{header: "InheritRDGatewayUserViaAPI", source: columnInheritance, field: "RDGatewayUserViaAPI"},
	{header: "InheritRDPAlertIdleTimeout", source: columnInheritance, field: "RDPAlertIdleTimeout"},
	{header: "InheritRDPMinutesToIdleTimeout", source: columnInheritance, field: "RDPMinutesToIdleTimeout"},
	{header: "InheritSoundQuality", source: columnInheritance, field: "SoundQuality"},
	{header: "InheritUserViaAPI", source: columnInheritance, field: "RedirectAudioCapture"},
	{header: "InheritRedirectAudioCapture", source: columnInheritance, field: "RDPVersion"},
	{header: "InheritRdpVersion", source: columnInheritance, field: "UserViaAPI"},
	{header: "InheritExternalCredentialProvider", source: columnInheritance, field: "ExternalCredentialProvider"},
}
