package ui

import (
	"fmt"
	"os"

	"github.com/mRemoteNG/mremoteng-go/internal/connection"
	xmlserialize "github.com/mRemoteNG/mremoteng-go/internal/serialize/xml"
)

// LoadConnectionsFile reads and decrypts an mRemoteNG connections file
// (Phase 1's internal/serialize/xml, already validated against a
// compatibility corpus generated by the original C# app) and returns its
// root container, ready to hand to NewConnectionTree. An empty password
// uses mRemoteNG's own default connection-file password, the same
// behavior internal/serialize/xml.Options.Password documents.
//
// This is the piece that actually satisfies Phase 2/3's shared "demo
// config file" exit criterion — no earlier stage owned wiring Phase 1's
// deserializer to the UI's tree, and it's a natural fit here alongside
// this stage's other persistence work (application settings).
func LoadConnectionsFile(path string, password []byte) (*connection.ContainerInfo, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("ui: read %s: %w", path, err)
	}
	doc, err := xmlserialize.Deserialize(data, xmlserialize.Options{Password: password})
	if err != nil {
		return nil, fmt.Errorf("ui: parse %s: %w", path, err)
	}
	return doc.Root, nil
}

// SaveConnectionsFile serializes root (Phase 1's XML v28 writer) and
// writes it to path. An empty password uses mRemoteNG's default
// connection-file password, same as LoadConnectionsFile.
func SaveConnectionsFile(path string, root *connection.ContainerInfo, password []byte) error {
	data, err := xmlserialize.Serialize(&xmlserialize.Document{Root: root}, xmlserialize.SerializeOptions{Password: password})
	if err != nil {
		return fmt.Errorf("ui: encode connections file: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("ui: write %s: %w", path, err)
	}
	return nil
}
