package xml

import "github.com/mRemoteNG/mremoteng-go/internal/connection"

func (d nodeDecoder) decode27(info *connection.ConnectionInfo, a attributes) {
	raw := &info.Raw
	raw.RedirectClipboard = a.boolean("RedirectClipboard")
	raw.Favorite = a.boolean("Favorite")
	raw.UseVMID = a.boolean("UseVmId")
	raw.VMID = a.string("VmId")
	raw.UseEnhancedMode = a.boolean("UseEnhancedMode")
	raw.RDPVersion = rdpVersionValue(a, "RdpVersion")
	raw.SSHTunnelConnectionName = a.string("SSHTunnelConnectionName")
	raw.OpeningCommand = a.string("OpeningCommand")
	raw.SSHOptions = a.string("SSHOptions")
	raw.RDPStartProgram = a.string("StartProgram")
	raw.RDPStartProgramWorkDir = a.string("StartProgramWorkDir")
	raw.DisableFullWindowDrag = a.boolean("DisableFullWindowDrag")
	raw.DisableMenuAnimations = a.boolean("DisableMenuAnimations")
	raw.DisableCursorShadow = a.boolean("DisableCursorShadow")
	raw.DisableCursorBlinking = a.boolean("DisableCursorBlinking")
	raw.ExternalCredentialProvider = credentialProviderValue(a, "ExternalCredentialProvider")
	raw.UserViaAPI = a.string("UserViaAPI")
	raw.ExternalAddressProvider = addressProviderValue(a, "ExternalAddressProvider")
	raw.VaultOpenbaoMount = a.string("VaultOpenbaoMount")
	raw.VaultOpenbaoRole = a.string("VaultOpenbaoRole")
	raw.VaultOpenbaoSecretEngine = vaultEngineValue(a, "VaultOpenbaoSecretEngine")
	raw.EC2InstanceID = a.string("EC2InstanceId")
	raw.EC2Region = a.string("EC2Region")
	raw.UseRestrictedAdmin = a.boolean("UseRestrictedAdmin")
	raw.UseRCG = a.boolean("UseRCG")
	raw.UseRedirectionServerName = a.boolean("UseRedirectionServerName")
	raw.RDGatewayExternalCredentialProvider = credentialProviderValue(a, "RDGatewayExternalCredentialProvider")
	raw.RDGatewayUserViaAPI = a.string("RDGatewayUserViaAPI")

	flags := &info.Inheritance
	flags.RedirectClipboard = a.boolean("InheritRedirectClipboard")
	flags.Favorite = a.boolean("InheritFavorite")
	flags.RDPVersion = a.boolean("InheritRdpVersion")
	flags.UseVMID = a.boolean("InheritUseVmId")
	flags.VMID = a.boolean("InheritVmId")
	flags.UseEnhancedMode = a.boolean("InheritUseEnhancedMode")
	flags.SSHTunnelConnectionName = a.boolean("InheritSSHTunnelConnectionName")
	flags.OpeningCommand = a.boolean("InheritOpeningCommand")
	flags.SSHOptions = a.boolean("InheritSSHOptions")
	flags.DisableFullWindowDrag = a.boolean("InheritDisableFullWindowDrag")
	flags.DisableMenuAnimations = a.boolean("InheritDisableMenuAnimations")
	flags.DisableCursorShadow = a.boolean("InheritDisableCursorShadow")
	flags.DisableCursorBlinking = a.boolean("InheritDisableCursorBlinking")
	flags.ExternalCredentialProvider = a.boolean("InheritExternalCredentialProvider")
	flags.UserViaAPI = a.boolean("InheritUserViaAPI")
	flags.UseRestrictedAdmin = a.boolean("InheritUseRestrictedAdmin")
	flags.UseRCG = a.boolean("InheritUseRCG")
	flags.UseRedirectionServerName = a.boolean("InheritUseRedirectionServerName")
	flags.RDGatewayExternalCredentialProvider = a.boolean("InheritRDGatewayExternalCredentialProvider")
	flags.RDGatewayUserViaAPI = a.boolean("InheritRDGatewayUserViaAPI")
}
